---
title: "Enos_Replication"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# I will be recreaeting all figures from the paper:
#   "What the Demolition of Public Housing Teaches Us
#      about the Impact of Racial Threat
#      on Political Behavior" by Ryan Enos

# Load libraries
library(ggplot2)
library(stargazer)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(apsrtable)
require(gridExtra)
require(simpleboot)
require(boot)
require(MatchIt)
require(zelig)

```

```{r dataCreation, cache = TRUE, include=FALSE}

data = read.csv('dataverse_files/data.turnout.csv')

```

```{r dataCreation2, include = FALSE, cache=TRUE}
##set some data as factors for use below
data$reg = as.Date(data$reg)
data$p = as.factor(data$p)
data$s = as.factor(data$s)

##distances used repeatedly in estimation below
dists = seq(from = 100, to = 1000, by = 100)


##basic diff in diffs in paper, estimated across multiple definitions of white and distances
cat('begin basic difference-in-differences estimation \n')

namepcts = c(seq(from = .91, to = .96, by = .01),.975,.99,1)

##matrices for stroing results
res.mat = matrix(nrow=length(namepcts),ncol=length(dists))

white.treat.N = res.mat
white.treat.effect.mean.boot = res.mat
white.treat.effect.conf.boot.lower = res.mat
white.treat.effect.conf.boot.upper = res.mat

black.treat.N = res.mat
black.treat.effect.mean.boot = res.mat
black.treat.effect.conf.boot.lower = res.mat
black.treat.effect.conf.boot.upper = res.mat

####################################

###registration is Illionis is cutoff 27 days prior to election day, limit to these individuals
use.data = data[data$reg<"2000-10-10"&is.na(data$reg)==F,]

##loop through definitions of white and distances and estimate at each combination
j <- 7
	##define a treatment and control group for each name percent
	useW = use.data[use.data$whitename>=namepcts[j],]
   useB = use.data[use.data$blackname>=namepcts[j],]
  
    for(h in 1:length(dists)){
      	Wtreat = useW[useW$demo.distance<=dists[h],]
      	Btreat = useB[useB$demo.distance<=dists[h],]
      	Wcont = useW[useW$demo.distance>dists[h],]
      	Bcont = useB[useB$demo.distance>dists[h],]     		
	
      	white.treat.N[j,h] = nrow(Wtreat)
      	black.treat.N[j,h] = nrow(Btreat)
	      	
	   ##for white and black subjects, perform t test of differences of means with boostrapped standard errors  	
		if(white.treat.N[j,h] > 0){
			white.boot = two.boot((Wtreat$vote2004-Wtreat$vote2000),(Wcont$vote2004-Wcont$vote2000),mean, R = 1000, na.rm=T)
			white.treat.effect.mean.boot[j,h] = white.boot$t0
		white.boot.ci = boot.ci(white.boot, type = 'basic')
			white.treat.effect.conf.boot.lower[j,h] = white.boot.ci$basic[4]
			white.treat.effect.conf.boot.upper[j,h] = white.boot.ci$basic[5]
		      		}
		      		
	if(black.treat.N[j,h] > 0){
		black.boot = two.boot((Btreat$vote2004-Btreat$vote2000),(Bcont$vote2004-Bcont$vote2000),mean, R = 1000, na.rm=T)
		black.treat.effect.mean.boot[j,h] = black.boot$t0
		black.boot.ci = boot.ci(black.boot, type = 'basic')
		black.treat.effect.conf.boot.lower[j,h] = black.boot.ci$basic[4]
		black.treat.effect.conf.boot.upper[j,h] = black.boot.ci$basic[5]		
		 }
		 }

```

```{r part2, include=FALSE }

##use data created above for whites
usedata = white.data


##create chunks for estimation
distances = seq(from = 10, to = 2000, by = 10)
areas = seq(from = 0, to = 1, length.out = length(distances))
			      
##storage bin
outmat.s = matrix(ncol = 5, nrow = 0)
outmat.d = matrix(ncol = 5, nrow = 0)

out.reg = zelig(vote2004~log(demo.distance)+log(context_black)+vote2000,data = usedata, model = 'ls', cite = F)

##begin simulations across variable values
#for(i in seq(1:length(distances))){
for(i in seq(1:length(distances))){
	print(i)
	ptm <- proc.time()  ##start time

	use.distance = distances[i]
	out.d.1 = setx(out.reg,
		vote2000 = 1,
		demo.distance = use.distance)

	out.d.sims = sim(out.reg,
		x = out.d.1)
	
	use.area = areas[i]	
	out.s.1 = setx(out.reg,
		vote2000 = 1,
		demo.distance = 100,
		context_black = use.area)

	out.s.sims = sim(out.reg,
		x = out.s.1)

	outstats.d = summary(out.d.sims)$stats[[1]]
	outstats.s = summary(out.s.sims)$stats[[1]]
	
	outmat.d = rbind(outmat.d,outstats.d)
	outmat.s = rbind(outmat.s,outstats.s)

	print(proc.time() - ptm)  ##end time
	}

##store results for graphics and table	
predicted.results.distance.vary.context = outmat.d
predicted.results.area.vary.context = outmat.s

out.reg.predictions = out.reg

```

```{r setup2, include=FALSE}

##create_tables_and_figures_only.r
###create output for Enos 'What the Demolition of Public Housing Teaches Us About the Impact of Racial Threat on Political Behavior' 
###RdE June 2014

###master graphic parameters for graphics 
ylims = c(-.35,.1)
ylims.2 = c(-.45,.1)
xlims = c(.5,11)
dists = seq(from = 1000, to = 100, by = -100) ###DELETE THIS LATER
xs = seq(1:length(dists))
ys = seq(from = -.35, to = .1, by = .05)
ys.lab = c('-0.35','-0.30', '-0.25','-0.20','-0.15','-0.10','-0.05','0.00','0.05','0.10')
ys.2 = seq(from = -.45, to = .1, by = .05)
ys.lab.2 = c('-0.45','-0.40','-0.35','-0.30', '-0.25','-0.20','-0.15','-0.10','-0.05','0.00','0.05','0.10')

offsets = .15
text.offsets = .025
cex.axis = .9
cex.N = .7
top.text.adj = c(1.3,1.3) ##offsets on labels to reduce crowding
bottom.text.adj = c(-.15,-.85)
point.size = 2
line.offset = .0175

```

## Figure 1

I was able to succesfully recreate all of figure 1.

```{r fig1, echo=FALSE}

#############################
# Figure 1: Treatment Effects
#############################

##load data

# For some reason, I had to turn the data into dataframe

wtreat = as.data.frame(white.treat.effect.mean.boot)
wtreat.lower = as.data.frame(white.treat.effect.conf.boot.lower)
wtreat.upper = as.data.frame(white.treat.effect.conf.boot.upper)
Nwtreat = as.data.frame(white.treat.N)

btreat = as.data.frame(black.treat.effect.mean.boot)
btreat.lower = as.data.frame(black.treat.effect.conf.boot.lower)
btreat.upper = as.data.frame(black.treat.effect.conf.boot.upper)
Nbtreat = as.data.frame(black.treat.N)

#wtreat2 = read.csv('dataverse_files/white.treat.effect.mean.boot.csv') 
#wtreat.lower2 = read.csv('dataverse_files/white.treat.effect.conf.boot.lower.csv') 
#wtreat.upper2 = read.csv('dataverse_files/white.treat.effect.conf.boot.upper.csv') 
#Nwtreat2 = read.csv('dataverse_files/white.treat.N.csv')
#btreat2 = read.csv('dataverse_files/black.treat.effect.mean.boot.csv') 
#btreat.lower2 = read.csv('dataverse_files/black.treat.effect.conf.boot.lower.csv') 
#btreat.upper2 = read.csv('dataverse_files/black.treat.effect.conf.boot.upper.csv') 
#Nbtreat2 = read.csv('dataverse_files/black.treat.N.csv')

##letters for marking graphs, one is not used
use.letters = c('a','b','c','d','e','f','skip','g','h')

##cycle through each line of data, each of which are groups defined by diferent namepcts
#for(i in 1:nrow(wtreat)){ ##turning into matrices helps below with segment function
i <- 7;

	use.wtreat = as.matrix(wtreat[i,])
	use.wlower = as.matrix(wtreat.lower[i,])
	use.wupper = as.matrix(wtreat.upper[i,])
	use.Nwtreat = as.matrix(Nwtreat[i,])
	
	use.btreat = as.matrix(btreat[i,])
	use.blower = as.matrix(btreat.lower[i,])
	use.bupper = as.matrix(btreat.upper[i,])
	use.Nbtreat = as.matrix(Nbtreat[i,])
	
##name graphs
#	if(i == 7){
#		pdf('output/Figure_1.pdf')
#	}
#	else{
#		pdf(paste('appendix_output/Figure_A1',use.letters[i],'.pdf',sep=''))
#		}			
	par(las = 1)
	par(mar = c(5.1, 4.1, .5, .5))
	plot(xs, use.wtreat,
		ylim = ylims,
		xlim = xlims,
		type = 'n',
		ylab = 'Treatment Effect',
		xlab = 'Treated Group Distance from Projects',
		xaxt = 'n',
		yaxt = 'n.csv')
	abline(h = 0, lty = 2)

###draw lines first because I want them to be covered by points
	####create spaces in lines using the offset (this allows the N to be displayed with the text() function)
	##black lines are offset to the left, white lines to the right	
	segments(x0= xs[1:2]+offsets, x1 = xs[1:2]+offsets, ##only do it for low N blacks because otherwise lines look funny
		y0 = use.btreat[,1:2], y1 =	use.blower[,1:2])
	segments(x0= xs[1:2]+offsets, x1 = xs[1:2]+offsets,
		y0 = use.btreat[,1:2] + line.offset, 	y1 =	use.bupper[,1:2])
  ##now the others
	segments(x0= xs[3:10]+offsets, x1 = xs[3:10]+offsets,
		y0 = use.blower[,3:10], 	y1 =	use.bupper[,3:10])
		
	segments(x0= xs-offsets, x1 = xs-offsets, ##bottomlines
		y0 = use.wtreat - line.offset, 	y1 =	use.wlower)
	segments(x0= xs-offsets, x1 = xs-offsets, ##toplines
		y0 = use.wtreat, 	y1 =	use.wupper)

  
  ##points and N descriptions
	points(xs-offsets, use.wtreat,
	       cex = point.size,
	       pch = 21, 
	       bg = 'white',
	       col = 'black')
	text(xs-offsets,use.wtreat,
	     paste('(',use.Nwtreat,')',sep = ''),
	     cex = cex.N,
	     #adj = top.text.adj
	     pos = 1
	    )
	
	points(xs+offsets, use.btreat,
	       pch = 16,
	       cex = point.size)
	text(xs+offsets,use.btreat,
	     paste('(',use.Nbtreat,')',sep = ''),
	     cex = cex.N,
	     #adj = bottom.text.adj
	     pos = 3
	    )
	
	axis(side = 1,
		at = xs,
		label = seq(100,1000,100),
		cex.axis = cex.axis
		)
	axis(side = 2,
		at = ys,
		label = ys.lab,
		cex.axis = cex.axis
		)	

	#dev.off()
```

## Figure 2

I was able to succesfully recreate all of figure 2.

```{r fig2, echo=FALSE}

#################
# Figures 2 
#################

##this cycles thorugh a bunch of dataframes, each of which is needed for a different graph
for(figure in c('white.demo.main')){
	if(figure == 'white.basic.main'){
		##this group is different than the rest because the second set is not actually a diff in diff, but calling it "diffs" for consistency
		treat = read.csv('dataverse_files/white.match.basic.csv')
		treat.2 = read.csv('dataverse_files/white.match.basic.property.csv')
		fig.nums = c('A3','A4') ##figure names
		pchs = c(17,17) ##point types
		}
	if(figure == 'white.demo.main'){
		treat = read.csv('dataverse_files/white.match.nondemolished.csv')
		diffs = read.csv('dataverse_files/white.match.nondemolished.diffs.csv')
		fig.nums = c('2','A5')
		pchs = c(17,22)
		}
	if(figure == 'white.demo.property'){
		treat = read.csv('dataverse_files/white.match.nondemolished.property.csv')
		diffs = read.csv('dataverse_files/white.match.nondemolished.diffs.property.csv')
		fig.nums = c('A6','A7')	
		pchs = c(17,22)
		}	
	if(figure == 'white.demo.localrace'){
		treat = read.csv('dataverse_files/white.match.nondemolished.localrace.csv')
		diffs = read.csv('dataverse_files/white.match.nondemolished.diffs.localrace.csv')
		fig.nums = c('A8','A9')			
		pchs = c(17,22)
		}
	if(figure == 'blackmain'){
		treat = read.csv('dataverse_files/white.match.black.property.csv')
		diffs = read.csv('dataverse_files/white.match.black.diffs.property.csv')
		fig.nums = c('3','A12')
		pchs = c(17,21)			
		}
	if(figure == 'blackcensus'){
		treat = read.csv('dataverse_files/white.match.black.csv')
		diffs = read.csv('dataverse_files/white.match.black.diffs.csv')
		fig.nums = c('A10','A11')
		pchs = c(17,21)	
		}


	##define axis for different graphs
	if(figure %in% c('white.basic.main','white.demo.main','blackmain')){
			use.ylims = ylims
			use.ys.lab = ys.lab
			use.ys = ys
		}
	else{
			use.ylims = ylims.2
			use.ys.lab = ys.lab.2
			use.ys = ys.2
		}

	##go through pairs for each pair of dataframe
	for(i in 1){
		if(i == 1){ 	
			use.treat = treat$coefficient			
			clower = use.treat-(1.96*treat$stdev)
			cupper = use.treat+(1.96*treat$stdev)
			use.N.treat = treat$N.treatment + treat$N.control
			}			
		if(i == 2 & figure != 'white.basic.main'){	
			use.treat = diffs$mean.diff			
			clower = diffs$low.ci
			cupper = diffs$high.ci
			use.N.treat = diffs$N
			}	
		if(i == 2 & figure == 'white.basic.main'){	##white.basic.main figures have slightly different structure 
			use.treat = treat.2$coefficient			
			clower = use.treat- (1.96*treat.2$stdev)
			cupper = use.treat+(1.96*treat.2$stdev)
			use.N.treat = treat.2$N.treatment + treat.2$N.control
			}
		if(figure %in% c('white.demo.main','blackmain') & i ==1){
				#pdf(paste('output/Figure_',fig.nums[i],'.pdf',sep=''))
				}
		else{	
			#pdf(paste('appendix_output/Figure_',fig.nums[i],'.pdf',sep=''))
			}
			par(las = 1)
			par(mar = c(5.1, 4.1, .5, .5))
			plot(xs, use.treat,
				ylim = use.ylims,
				xlim = xlims,
				type = 'n',
				ylab = 'Treatment Effect',
				xlab = 'Treated Group Distance from Projects',
				xaxt = 'n',
				yaxt = 'n')
			abline(h = 0, lty = 2)
				
			segments(x0=xs,x1=xs,
						y0= use.treat+line.offset,y1=cupper)
			segments(x0=xs,x1=xs,
						y0= use.treat,y1=clower)

		### Treatment Effects
			points(xs, use.treat, 
				pch = pchs[i], 
				cex = point.size,
					bg = 'white',
       			col = 'black')
			text(xs,use.treat,
			     paste('(',use.N.treat,')',sep = ''),
			     cex = cex.N,
			     pos = 3
			  )
			axis(side = 1,
					at = xs,
					label = seq(100,1000,100),
					cex.axis = cex.axis
					)
			axis(side = 2,
					at = use.ys,
					label = use.ys.lab,
					cex.axis = cex.axis
					)	
			
		}
	}	


```

##Figure 3

I was able to succesfully recreate all of figure 3.

```{r fig3, echo=FALSE}

#################
# Figures 3
#################

##this cycles thorugh a bunch of dataframes, each of which is needed for a different graph
for(figure in c('blackmain')){
	if(figure == 'white.basic.main'){
		##this group is different than the rest because the second set is not actually a diff in diff, but calling it "diffs" for consistency
		treat = read.csv('dataverse_files/white.match.basic.csv')
		treat.2 = read.csv('dataverse_files/white.match.basic.property.csv')
		fig.nums = c('A3','A4') ##figure names
		pchs = c(17,17) ##point types
		}
	if(figure == 'white.demo.main'){
		treat = read.csv('dataverse_files/white.match.nondemolished.csv')
		diffs = read.csv('dataverse_files/white.match.nondemolished.diffs.csv')
		fig.nums = c('2','A5')
		pchs = c(17,22)
		}
	if(figure == 'white.demo.property'){
		treat = read.csv('dataverse_files/white.match.nondemolished.property.csv')
		diffs = read.csv('dataverse_files/white.match.nondemolished.diffs.property.csv')
		fig.nums = c('A6','A7')	
		pchs = c(17,22)
		}	
	if(figure == 'white.demo.localrace'){
		treat = read.csv('dataverse_files/white.match.nondemolished.localrace.csv')
		diffs = read.csv('dataverse_files/white.match.nondemolished.diffs.localrace.csv')
		fig.nums = c('A8','A9')			
		pchs = c(17,22)
		}
	if(figure == 'blackmain'){
		treat = read.csv('dataverse_files/white.match.black.property.csv')
		diffs = read.csv('dataverse_files/white.match.black.diffs.property.csv')
		fig.nums = c('3','A12')
		pchs = c(17,21)			
		}
	if(figure == 'blackcensus'){
		treat = read.csv('dataverse_files/white.match.black.csv')
		diffs = read.csv('dataverse_files/white.match.black.diffs.csv')
		fig.nums = c('A10','A11')
		pchs = c(17,21)	
		}


	##define axis for different graphs
	if(figure %in% c('white.basic.main','white.demo.main','blackmain')){
			use.ylims = ylims
			use.ys.lab = ys.lab
			use.ys = ys
		}
	else{
			use.ylims = ylims.2
			use.ys.lab = ys.lab.2
			use.ys = ys.2
		}

	##go through pairs for each pair of dataframe
	for(i in 1){
		if(i == 1){ 	
			use.treat = treat$coefficient			
			clower = use.treat-(1.96*treat$stdev)
			cupper = use.treat+(1.96*treat$stdev)
			use.N.treat = treat$N.treatment + treat$N.control
			}			
		if(i == 2 & figure != 'white.basic.main'){	
			use.treat = diffs$mean.diff			
			clower = diffs$low.ci
			cupper = diffs$high.ci
			use.N.treat = diffs$N
			}	
		if(i == 2 & figure == 'white.basic.main'){	##white.basic.main figures have slightly different structure 
			use.treat = treat.2$coefficient			
			clower = use.treat- (1.96*treat.2$stdev)
			cupper = use.treat+(1.96*treat.2$stdev)
			use.N.treat = treat.2$N.treatment + treat.2$N.control
			}
		if(figure %in% c('white.demo.main','blackmain') & i ==1){
				#pdf(paste('output/Figure_',fig.nums[i],'.pdf',sep=''))
				}
		else{	
			#pdf(paste('appendix_output/Figure_',fig.nums[i],'.pdf',sep=''))
			}
			par(las = 1)
			par(mar = c(5.1, 4.1, .5, .5))
			plot(xs, use.treat,
				ylim = use.ylims,
				xlim = xlims,
				type = 'n',
				ylab = 'Treatment Effect',
				xlab = 'Treated Group Distance from Projects',
				xaxt = 'n',
				yaxt = 'n')
			abline(h = 0, lty = 2)
				
			segments(x0=xs,x1=xs,
						y0= use.treat+line.offset,y1=cupper)
			segments(x0=xs,x1=xs,
						y0= use.treat,y1=clower)

		### Treatment Effects
			points(xs, use.treat, 
				pch = pchs[i], 
				cex = point.size,
					bg = 'white',
       			col = 'black')
			text(xs,use.treat,
			     paste('(',use.N.treat,')',sep = ''),
			     cex = cex.N,
			     pos = 3
			  )
			axis(side = 1,
					at = xs,
					label = seq(100,1000,100),
					cex.axis = cex.axis
					)
			axis(side = 2,
					at = use.ys,
					label = use.ys.lab,
					cex.axis = cex.axis
					)	
			
		}
	}	

```


###Figure 4

I was able to succesfully recreate all of figure 4.

```{r fig4, echo=FALSE}

###Figure 4
###################################

distdat =  read.csv('dataverse_files/predicted.results.distance.vary.context.csv')
areadat = read.csv('dataverse_files/predicted.results.area.vary.context.csv')

##new ylims for these graphs
ylims.predict = c(.6,.75)

datas = list(distdat,areadat)##put data in a list to cycle through
##parameters to be used in graphs below
xs = list(seq(from = 10, to = 2000, by = 10), seq(from = 45000, to = 1004000, by = 4800)/1000)
use.letters = c('a','b')
xlabs = c('Distance from Project','Percent of Local Black Population in Demolished Project')
ylabs = c(expression(Pr(vote[2004])),'')
vlines = list(seq(from = 0, to = 2000, by = 200),seq(from = 0, to = 1000, by = 100))
axis.labs = list(as.character(seq(from = 0, to = 2000, by = 200)),
	as.character(c('0','10%','20%','30%','40%','50%','60%','70%','80%','90%','100%')))


	colnames(datas[[1]]) = c("mean","sd","50%","2.5%","97.5%") ##saving renames columns, so name back
		par(las = 1)
		par(mar = c(5.1, 4.1, .5, .5))
		
		plot(xs[[1]],datas[[1]][,'mean'],
			type = 'l',
			xlab = xlabs[1],
			ylab = ylabs[1],
			ylim = ylims.predict,
			xaxt = 'n',
			cex.axis = cex.axis,
			lwd = 4
		)
		
	##put horizontal and vertical lines on plots
	abline(h = seq(from = min(ylims.predict), to = max(ylims.predict), by = .025),
	       lty = 2,
	       col = 'gray',
	       lwd = 1)
	abline(v = vlines[[i]], 
	       lty = 2,
	       col = 'gray',
	       lwd = 1)
	lines(xs[[1]],datas[[1]][,'2.5%'],
			lty = 3,
			lwd = 2.5)
	lines(xs[[1]],datas[[1]][,'97.5%'],
			lty = 3,
			lwd = 2.5)
	axis(side = 1, 
		at = vlines[[1]], 
		labels = axis.labs[[1]],
		cex.axis = cex.axis)
	
	p1 <- recordPlot()
	
	
		colnames(datas[[2]]) = c("mean","sd","50%","2.5%","97.5%") ##saving renames columns, so name back
		par(las = 1)
		par(mar = c(5.1, 4.1, .5, .5))
		
		plot(xs[[2]],datas[[2]][,'mean'],
			type = 'l',
			xlab = xlabs[2],
			ylab = ylabs[2],
			ylim = ylims.predict,
			xaxt = 'n',
			cex.axis = cex.axis,
			lwd = 4
		)
		
	##put horizontal and vertical lines on plots
	abline(h = seq(from = min(ylims.predict), to = max(ylims.predict), by = .025),
	       lty = 2,
	       col = 'gray',
	       lwd = 1)
	abline(v = vlines[[i]], 
	       lty = 2,
	       col = 'gray',
	       lwd = 1)
	lines(xs[[2]],datas[[2]][,'2.5%'],
			lty = 3,
			lwd = 2.5)
	lines(xs[[2]],datas[[2]][,'97.5%'],
			lty = 3,
			lwd = 2.5)
	axis(side = 1, 
		at = vlines[[2]], 
		labels = axis.labs[[2]],
		cex.axis = cex.axis)
	
	p2 <- recordPlot()
	
par(mfrow=c(2,2))


```

###Figure 5 and 6

I was able to succesfully recreate all of figures 5 and 6

```{r fig5, echo=FALSE}

###########################################
###vote choice graphs################
###Figures 5 and 6
###################################
pres.elections = c('dole_pct_ei','bush2000_pct_ei','bush2004_pct_ei','mccain_pct_ei')
obama.elections = c('obama_sen_primary_pct_ei','keyes_pct_ei','obama_pres_primary_pct_ei')

dists = read.csv('dataverse_files/distance.vote.differences.csv')
demos = read.csv('dataverse_files/demolished.vote.differences.csv')


graphs = c('5a','5b','6')

for(i in graphs){

	if(i == '5a'){dat = dists}
	else{dat = demos}
		
	if(i %in% c('5a','5b')){
		xlims = c(.75,4.25)
		ylims = c(-.1,.2)	
		}
	else{
		xlims = c(.75,3.25)
		ylims = c(-.1,.25)
		}

	##recode Keyes to Obama general for presentation purposes
	dat[dat$election == 'keyes_pct_ei','x.mean'] = 1 - dat[dat$election == 'keyes_pct_ei','x.mean']
	dat[dat$election == 'keyes_pct_ei','y.mean'] = 1 - dat[dat$election == 'keyes_pct_ei','y.mean']
	dat[dat$election == 'keyes_pct_ei','diff'] =dat[dat$election == 'keyes_pct_ei','y.mean'] - dat[dat$election == 'keyes_pct_ei','x.mean']
	
		par(las = 1)
		par(mar = c(5.1, 4.1, .5, 1.5))
		plot(seq(1:4),
			rep(1,4),
			ylim = ylims,
			xlim = xlims, 
			type = 'n',
			xaxt = 'n',
			yaxt = 'n',
			xlab = 'Election',
			ylab = ifelse(i == '5b','','Treatment Effect')
			)
		abline(h=0, lty = 2)
		
		if(i %in% c('5a','5b')){
			segments(
				x0= seq(1:4)-offsets, 
				x1 = seq(1:4)-offsets,
				y0 = dat[dat$group == 'white'&dat$election %in% pres.elections,'diff']-(1.96*dat[dat$group == 'white'&dat$election %in% pres.elections,'sd']),
				y1 =	dat[dat$group == 'white'&dat$election %in% pres.elections,'diff']+(1.96*dat[dat$group == 'white'&dat$election %in% pres.elections,'sd'])	
					)
			points(seq(1:4)-offsets,
				dat[dat$group == 'white'&dat$election %in% pres.elections,'diff'],
					pch = 21, 
					bg = 'white',
					col = 'black',
					cex = 2
				)
			segments(
				x0= seq(1:4)+offsets, 
				x1 = seq(1:4)+offsets,
				y0 = dat[dat$group == 'black'&dat$election %in% pres.elections,'diff']-(1.96*dat[dat$group == 'black'&dat$election %in% pres.elections,'sd']),
				y1 =	dat[dat$group == 'black'&dat$election %in% pres.elections,'diff']+(1.96*dat[dat$group == 'black'&dat$election %in% pres.elections,'sd'])	
					)
			points(seq(1:4)+offsets,
				dat[dat$group == 'black'&dat$election %in% pres.elections,'diff'],
					pch = 16,
					cex = 2
				)
			axis(side = 1, at = seq(1:4), 
				c('1996','2000','2004','2008'), 
				tick = F,
				cex.axis = cex.axis)		
			}
		else{
			segments(
				x0= seq(1:3)-offsets, 
				x1 = seq(1:3)-offsets,
				y0 = dat[dat$group == 'white'&dat$election %in% obama.elections,'diff']-(1.96*dat[dat$group == 'white'&dat$election %in% obama.elections,'sd']),
				y1 =	dat[dat$group == 'white'&dat$election %in% obama.elections,'diff']+(1.96*dat[dat$group == 'white'&dat$election %in% obama.elections,'sd'])	
					)
			points(seq(1:3)-offsets,
				dat[dat$group == 'white'&dat$election %in% obama.elections,'diff'],
					pch = 21, 
					bg = 'white',
					col = 'black',
					cex = 2
				)
			segments(
				x0= seq(1:3)+offsets, 
				x1 = seq(1:3)+offsets,
				y0 = dat[dat$group == 'black'&dat$election %in% obama.elections,'diff']-(1.96*dat[dat$group == 'black'&dat$election %in% obama.elections,'sd']),
				y1 =	dat[dat$group == 'black'&dat$election %in% obama.elections,'diff']+(1.96*dat[dat$group == 'black'&dat$election %in% obama.elections,'sd'])	
					)
  			points(seq(1:3)+offsets,
				dat[dat$group == 'black'&dat$election %in% obama.elections,'diff'],
					pch = 16,
					cex = 2
				)
		axis(side = 1, at = seq(1:3), 
					c('2004 \n Senate Primary','2004 \n Senate General','2008 \n President Primary'),
					tick = F,
					cex.axis = cex.axis
					)
		
			}	
		axis(side = 2,
			at = seq(from = -.1, to = .3, by = .05),
			label = c('-0.10','-0.05','0.00','0.05','0.10','0.15','0.20','0.25','0.30'),
			cex.axis = cex.axis
			)			
	}		
				

```




```{r fig6, echo=FALSE}



```


